Delete post functionality added
Ajdj100/proj_6_web pull request #71
Opened 2024-02-03 11:40 UTC by Ajdj100

A new endpoint for deleting posts has been added, and a button was added to your profile page which allows you to delete your own posts while browsing them. It may be too easy right now to delete a post and might be accidentally hit. Could be worth to add some sort of confirmation in the future.

2024-02-03 11:40 UTC, Ajdj100 commented
this should close #70

2024-02-05 20:09 UTC, sebastian-j-ibanez requested changes
Added a few comments. Let me know what you think :mate:

2024-02-05 20:09 UTC, sebastian-j-ibanez commented on Public/Profile.html
> +        fetch("http://localhost:8000/post", {
I do not believe this route exists yet. The only DELETE route I see is for "/", and is intended to delete comments.

2024-02-05 20:09 UTC, sebastian-j-ibanez commented on Routes/post.js
> +router.delete('/', function (req, res) {
I think we should change this DELETE route from "/" to "/comment" to be more specific about what's being deleted.

2024-02-05 20:20 UTC, sebastian-j-ibanez commented on Public/Profile.html
> +        fetch("http://localhost:8000/post", {
I misunderstood how the route seperation worked. This is properly implemented.

2024-02-07 13:30 UTC, sebastian-j-ibanez approved these changes
Looks good :mate:

2024-02-07 13:30 UTC, merged